ARDUINO_DIR = /opt/arduino-1.8.16
ARDMK_DIR = ../Arduino-Makefile
USER_LIB_PATH = ../libraries
#AVR_TOOLS_DIR = /usr
AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr
AVRDUDE_CONF = /usr/share/arduino/hardware/tools/avrdude.conf
BOARD_TAG = mega
BOARD_SUB = atmega2560
ARDUINO_LIBS = ros_lib StepperDriver FlexyStepper
include $(ARDMK_DIR)/Arduino.mk
